version: '3.7'
services:
  tictactoe:
    build:
      context: .
      dockerfile: chupacabra_server/app/tic_tac_toe/Dockerfile
    ports:
      - "7654:80"

  chupacabra:
    build:
      context: .
      dockerfile: chupacabra_server/app/chupacabra_server/Dockerfile
    ports:
      - "7653:80"

  chupacabra_flask:
    build:
      context: .
      dockerfile: chupacabra_server/app/flask_server/Dockerfile
    ports:
      - "7655:80"

  redis:
    image: redis:alpine
    ports:
      - "7652:6379"

  # Really, this should be a persistent db.
  postgres:
    build: ./postgres/.
    ports:
      - "7651:5432"
