# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from chupacabra_client.protos import chupacabra_pb2 as chupacabra__client_dot_protos_dot_chupacabra__pb2
from chupacabra_client.protos import game_structs_pb2 as chupacabra__client_dot_protos_dot_game__structs__pb2


class ChupacabraServerStub(object):
  """Defines the service
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RegisterUser = channel.unary_unary(
        '/chupacabra.ChupacabraServer/RegisterUser',
        request_serializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.UserRequest.SerializeToString,
        response_deserializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.UserResponse.FromString,
        )
    self.BeginSession = channel.unary_unary(
        '/chupacabra.ChupacabraServer/BeginSession',
        request_serializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.SessionRequest.SerializeToString,
        response_deserializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.SessionResponse.FromString,
        )
    self.ListAvailableGames = channel.unary_unary(
        '/chupacabra.ChupacabraServer/ListAvailableGames',
        request_serializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.PlayerGameInfo.SerializeToString,
        response_deserializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.AvailableGamesResponse.FromString,
        )
    self.RequestGame = channel.unary_unary(
        '/chupacabra.ChupacabraServer/RequestGame',
        request_serializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.GameRequest.SerializeToString,
        response_deserializer=chupacabra__client_dot_protos_dot_game__structs__pb2.GameRequestResponse.FromString,
        )
    self.CheckGameRequest = channel.unary_unary(
        '/chupacabra.ChupacabraServer/CheckGameRequest',
        request_serializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.GameRequestStatus.SerializeToString,
        response_deserializer=chupacabra__client_dot_protos_dot_game__structs__pb2.GameRequestStatusResponse.FromString,
        )
    self.GetGameState = channel.unary_unary(
        '/chupacabra.ChupacabraServer/GetGameState',
        request_serializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.PlayerGameInfo.SerializeToString,
        response_deserializer=chupacabra__client_dot_protos_dot_game__structs__pb2.GameStatusResponse.FromString,
        )
    self.CheckLegalMoves = channel.unary_unary(
        '/chupacabra.ChupacabraServer/CheckLegalMoves',
        request_serializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.PlayerGameInfo.SerializeToString,
        response_deserializer=chupacabra__client_dot_protos_dot_game__structs__pb2.LegalMovesResponse.FromString,
        )
    self.MakeMove = channel.unary_unary(
        '/chupacabra.ChupacabraServer/MakeMove',
        request_serializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.MoveRequest.SerializeToString,
        response_deserializer=chupacabra__client_dot_protos_dot_game__structs__pb2.GameStatusResponse.FromString,
        )
    self.ForfeitGame = channel.unary_unary(
        '/chupacabra.ChupacabraServer/ForfeitGame',
        request_serializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.PlayerGameInfo.SerializeToString,
        response_deserializer=chupacabra__client_dot_protos_dot_game__structs__pb2.GameStatusResponse.FromString,
        )


class ChupacabraServerServicer(object):
  """Defines the service
  """

  def RegisterUser(self, request, context):
    """Register a new user
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BeginSession(self, request, context):
    """Begin a new session
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListAvailableGames(self, request, context):
    """List games available on the server
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RequestGame(self, request, context):
    """Request a new game
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckGameRequest(self, request, context):
    """Check if the game is available
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetGameState(self, request, context):
    """Get the game state
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CheckLegalMoves(self, request, context):
    """See what legal moves are available
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MakeMove(self, request, context):
    """Try to make a move
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ForfeitGame(self, request, context):
    """Forfeit the game
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChupacabraServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RegisterUser': grpc.unary_unary_rpc_method_handler(
          servicer.RegisterUser,
          request_deserializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.UserRequest.FromString,
          response_serializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.UserResponse.SerializeToString,
      ),
      'BeginSession': grpc.unary_unary_rpc_method_handler(
          servicer.BeginSession,
          request_deserializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.SessionRequest.FromString,
          response_serializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.SessionResponse.SerializeToString,
      ),
      'ListAvailableGames': grpc.unary_unary_rpc_method_handler(
          servicer.ListAvailableGames,
          request_deserializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.PlayerGameInfo.FromString,
          response_serializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.AvailableGamesResponse.SerializeToString,
      ),
      'RequestGame': grpc.unary_unary_rpc_method_handler(
          servicer.RequestGame,
          request_deserializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.GameRequest.FromString,
          response_serializer=chupacabra__client_dot_protos_dot_game__structs__pb2.GameRequestResponse.SerializeToString,
      ),
      'CheckGameRequest': grpc.unary_unary_rpc_method_handler(
          servicer.CheckGameRequest,
          request_deserializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.GameRequestStatus.FromString,
          response_serializer=chupacabra__client_dot_protos_dot_game__structs__pb2.GameRequestStatusResponse.SerializeToString,
      ),
      'GetGameState': grpc.unary_unary_rpc_method_handler(
          servicer.GetGameState,
          request_deserializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.PlayerGameInfo.FromString,
          response_serializer=chupacabra__client_dot_protos_dot_game__structs__pb2.GameStatusResponse.SerializeToString,
      ),
      'CheckLegalMoves': grpc.unary_unary_rpc_method_handler(
          servicer.CheckLegalMoves,
          request_deserializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.PlayerGameInfo.FromString,
          response_serializer=chupacabra__client_dot_protos_dot_game__structs__pb2.LegalMovesResponse.SerializeToString,
      ),
      'MakeMove': grpc.unary_unary_rpc_method_handler(
          servicer.MakeMove,
          request_deserializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.MoveRequest.FromString,
          response_serializer=chupacabra__client_dot_protos_dot_game__structs__pb2.GameStatusResponse.SerializeToString,
      ),
      'ForfeitGame': grpc.unary_unary_rpc_method_handler(
          servicer.ForfeitGame,
          request_deserializer=chupacabra__client_dot_protos_dot_chupacabra__pb2.PlayerGameInfo.FromString,
          response_serializer=chupacabra__client_dot_protos_dot_game__structs__pb2.GameStatusResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'chupacabra.ChupacabraServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
